# Generated by Django 3.0.9 on 2020-08-20 12:27

import autoslug.fields
from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0002_auto_20200820_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name': 'Brewery', 'verbose_name_plural': 'Breweries'},
        ),
        migrations.AddField(
            model_name='brewery',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default_slug', editable=False, populate_from='title', unique=True, verbose_name='Brewery Slug'),
            preserve_default=False,
        ),
    ]
