# Generated by Django 3.0.9 on 2020-10-30 10:19

import beerhunter.breweries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_brewery_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='image',
            field=models.ImageField(blank=True, default='images/default/fermentation.png', null=True, upload_to=beerhunter.breweries.models.brewery_directory_path_with_uuid),
        ),
    ]
