# Generated by Django 3.0.9 on 2020-08-24 17:29

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AromaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title of Hop')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Hop Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alpha_min', models.FloatField(blank=True, null=True)),
                ('alpha_max', models.FloatField(blank=True, null=True)),
                ('beta_min', models.FloatField(blank=True, null=True)),
                ('beta_max', models.FloatField(blank=True, null=True)),
                ('oil_min', models.FloatField(blank=True, null=True)),
                ('oil_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
