# Generated by Django 3.0.9 on 2020-08-24 17:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin'),
        ),
    ]
