# Generated by Django 3.0.9 on 2020-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_hop_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='aroma_profile',
            field=models.ManyToManyField(blank=True, related_name='aroma_profile', to='hops.AromaProfile'),
        ),
    ]
