# Generated by Django 3.0.9 on 2020-08-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='og',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
