# Generated by Django 3.0.9 on 2020-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20200819_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'verbose_name': 'Beer', 'verbose_name_plural': 'Beers'},
        ),
    ]
