# Generated by Django 3.0.9 on 2020-08-20 11:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
        ('beers', '0004_beer_brewery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brewered_by', to='breweries.Brewery'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from='title', unique=True, verbose_name='Beer Slug'),
        ),
    ]
