# Generated by Django 3.0.9 on 2020-10-02 09:33

import beerhunter.beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_beer_hunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(default='', upload_to=beerhunter.beers.models.beer_directory_path_with_uuid),
            preserve_default=False,
        ),
    ]
