# Generated by Django 3.0.9 on 2020-10-02 13:53

import beerhunter.beers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_brewery_country_of_origin'),
        ('beers', '0007_beer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brewered_by', to='breweries.Brewery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_beer.png', upload_to=beerhunter.beers.models.beer_directory_path_with_uuid),
        ),
        migrations.AlterField(
            model_name='beer',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title of Beer'),
        ),
    ]
