# Generated by Django 3.0.9 on 2020-10-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_brewery_country_of_origin'),
        ('beers', '0008_auto_20201002_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('short_title',),
            },
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brewered_by', to='breweries.Brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.Style'),
        ),
    ]
