# Generated by Django 3.0.9 on 2020-10-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_auto_20201002_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.Style'),
        ),
    ]
