# Generated by Django 3.0.9 on 2020-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0004_brewery_country_of_origin'),
        ('beers', '0010_auto_20201002_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brewered', to='breweries.Brewery'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers_with_style', to='beers.Style'),
        ),
    ]
