# Generated by Django 3.0.9 on 2020-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_auto_20201002_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('title',), 'verbose_name': 'Beer', 'verbose_name_plural': 'Beers'},
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(fields=('title', 'version', 'brewery'), name='beer_constraint'),
        ),
    ]
