# Generated by Django 3.0.9 on 2020-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0004_auto_20200824_2130'),
        ('beers', '0015_auto_20201019_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='hops',
            field=models.ManyToManyField(blank=True, related_name='brewed_beers', to='hops.Hop'),
        ),
    ]
